title = "Saads perfektewelt"
baseURL = '/'
languageCode = 'en-us'

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]

[taxonomies]
  tag = "tags"


[params]
  # "relatedtext" is the text that appears above the tag list at the bottom of pages.
  relatedtext = "Related"
  favicon = "/favicon.ico"
  math = true


  #list items
  datesinlist = true
  authorsinlist = true
  taglist = true
  #footer items
  nextprev = true

  showrss = true
